name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v3

            # Step 2: Remove Default Go Installation
            - name: Remove Default Go Installation
              run: |
                  sudo rm -rf /usr/local/go
                  sudo rm -rf /opt/hostedtoolcache/go

            # Step 3: Set up Go
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.21

            # Step 4: Check Go Version After Setup
            - name: Check Go Version After Setup
              run: |
                  go version
                  which go

            # Step 5: Prepare the Go environment
            - name: Prepare Go environment
              run: |
                  go mod tidy

            # Step 6: Build the static site
            - name: Build static site
              run: |
                  go run ./cmd/website

            # Step 7: Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
