name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Checkout the repository
            - name: Checkout repository
              uses: actions/checkout@v3

            # Step 2: Set up Go
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20

            # Step 3: Debug Go Environment
            - name: Debug Go Environment
              run: |
                  go version
                  go env
                  which go

            # Step 4: Enable Go Modules
            - name: Enable Go Modules
              run: |
                  export GO111MODULE=on

            # Step 5: Prepare the Go environment
            - name: Prepare Go environment
              run: |
                  go mod tidy

            # Step 6: Build the static site
            - name: Build static site
              run: |
                  go run ./cmd/website

            # Step 7: Deploy to GitHub Pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./build
